function(edge_tts_setup_options)
    option(EDGE_TTS_BUILD_APPS      "Build the edge-tts and edge-playback CLI apps" ON)
    option(EDGE_TTS_BUILD_TESTS     "Build the per-module test suites" ON)
    option(EDGE_TTS_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
    option(EDGE_TTS_ENABLE_NETWORK_TESTS "Enable tests that call the live Edge TTS service" OFF)
    option(EDGE_TTS_ENABLE_SANITIZERS   "Enable address/UB sanitizers in supported compilers" OFF)
    option(EDGE_TTS_ENABLE_CLANG_TIDY   "Run clang-tidy on all compiled sources" OFF)
endfunction()
