#pragma once

#include "edge_tts/common/IdGenerator.hpp"

#include <string>

namespace edge_tts::communication {

// A pair of identifiers required for one Edge TTS WebSocket request cycle.
//
// Reference: communicate.py
//   connect_id() = uuid.uuid4().hex  — UUID v4 without hyphens, 32 lowercase hex chars
//
//   ConnectionId → appended to the WebSocket URL:
//     f"{WSS_URL}&ConnectionId={connect_id()}"
//   request_id  → placed in the X-RequestId header of the SSML frame:
//     f"X-RequestId:{request_id}\r\n..."
//
// Both IDs are generated by separate calls to connect_id(), so they are
// always distinct values.  The speech.config frame does NOT carry X-RequestId.
struct ConnectionMetadata {
    std::string connection_id;  // 32 lowercase hex chars, no hyphens
    std::string request_id;     // 32 lowercase hex chars, no hyphens
};

// Generates ConnectionMetadata pairs using the injected IdGenerator.
//
// Each call to create_for_request() produces a fresh ConnectionMetadata with
// two independently generated UUID v4 values (matching Python's two separate
// calls to connect_id()).
//
// The IdGenerator is held by reference — callers own the generator and must
// ensure it outlives the factory.
class ConnectionMetadataFactory {
public:
    explicit ConnectionMetadataFactory(common::IdGenerator& ids) noexcept;

    // Returns a new ConnectionMetadata with freshly generated IDs.
    [[nodiscard]] ConnectionMetadata create_for_request();

private:
    common::IdGenerator& ids_;
};

} // namespace edge_tts::communication
